### ISSUE TITLE
Vagrant up is not working

### ISSUE THREAD

**Issue by the-destro** [3ofcoins/jetpack#5]
It is asking for a password during this step of vagrant up:
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:

**Comment by mtpereira** [comment]
Hi,

I actually got stuck on the same issue, which really isn't an issue:
Vagrant is asking for your local user password, so that it starts a local
NFS daemon on your workstation.

I hope this helps! :)

On Mon, May 4, 2015 at 6:48 PM, the-destro <notifications@github.com> wrote:

> It is asking for a password during this step of vagrant up:
> ==> default: Preparing to edit /etc/exports. Administrator privileges will
> be required...
> Password:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3ofcoins/jetpack/issues/5>.
>



-- 
Manuel Tiago Pereira

**Comment by mpasternacki** [comment]
What @mtpereira said: this is asking for your host password to export NFS-shared filesystems (Vagrant needs root to edit `/etc/exports` on host). Not an issue with Jetpack.
